// <auto-generated />
using System;
using MedicalRecordService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalRecordService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620200417_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalRecordService.Domain.Entities.EventoArmazenado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdAgregado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_agregado");

                    b.Property<string>("Metadados")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadados");

                    b.Property<DateTime>("OcorreuEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorreu_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("TipoAgregado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_agregado");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_evento");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.HasIndex("IdAgregado", "Versao")
                        .IsUnique();

                    b.ToTable("repositorio_eventos", (string)null);
                });

            modelBuilder.Entity("MedicalRecordService.Domain.Entities.LogAcessoProntuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("AcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acessado_em");

                    b.Property<Guid>("IdProntuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_prontuario");

                    b.Property<Guid>("IdUsuarioAcesso")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario_acesso");

                    b.HasKey("Id");

                    b.ToTable("log_acesso_prontuario", (string)null);
                });

            modelBuilder.Entity("MedicalRecordService.Infrastructure.Outbox.EventoSaida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdAgregado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_agregado");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("TipoAgregado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_agregado");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.ToTable("eventos_saida", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
