// <auto-generated />
using System;
using AppointmentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppointmentService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentService.Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AgendadoPara")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agendado_para");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minutos");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_medico");

                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_paciente");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdMedico", "AgendadoPara");

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.EstadoSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EtapaAtual")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etapa_atual");

                    b.Property<Guid>("IdCorrelacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_correlacao");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TipoSaga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_saga");

                    b.HasKey("Id");

                    b.HasIndex("IdCorrelacao")
                        .IsUnique();

                    b.ToTable("estado_saga", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.GradeHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<int>("DuracaoSlotMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_slot_minutos");

                    b.Property<TimeOnly>("HorarioFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_fim");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_inicio");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_medico");

                    b.HasKey("Id");

                    b.HasIndex("IdMedico", "DiaSemana");

                    b.ToTable("grade_horarios", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.HorarioBloqueado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("FimEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim_em");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_medico");

                    b.Property<DateTime>("InicioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_em");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo");

                    b.HasKey("Id");

                    b.HasIndex("IdMedico", "InicioEm");

                    b.ToTable("horarios_bloqueados", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Infrastructure.Outbox.EventoSaida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdAgregado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_agregado");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("TipoAgregado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_agregado");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.ToTable("eventos_saida", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
