// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621230134_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.LogEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<Guid>("IdDestinatario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_destinatario");

                    b.Property<Guid>("IdEvento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_evento");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_erro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento", "TipoEvento", "Canal")
                        .IsUnique();

                    b.ToTable("logs_envio", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.ModeloNotificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assunto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assunto");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<string>("CorpoModelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo_modelo");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("TipoEvento", "Canal")
                        .IsUnique();

                    b.ToTable("modelos_notificacao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
